added english text in problem 12189
qarakusi-am/qarakusi.am pull request #103
Opened 2022-11-26 08:00 UTC by Gor397

2022-11-26 19:01 UTC, zidder requested changes

2022-11-26 19:01 UTC, zidder commented on scenes/enumerated/problem_12189/english_text.py
> +condition2_string = "Condition $2$: ", r"Vazgen would have three times more than Armen, \\    if he collected $5$ more mushrooms"
Bob, Simon?

2022-11-26 19:48 UTC, Gor397 commented on scenes/enumerated/problem_12189/english_text.py
> +condition2_string = "Condition $2$: ", r"Vazgen would have three times more than Armen, \\    if he collected $5$ more mushrooms"
անունները փոխեցի, պայմաններում մոռացա փոխեմ ։դ, կդզեմ էտ

2022-12-04 10:33 UTC, zidder approved these changes

2022-12-04 13:26 UTC, merged