problem_12695
qarakusi-am/qarakusi.am pull request #147
Opened 2023-02-14 13:14 UTC by AlternativeFuture

2023-02-15 11:05 UTC, zidder commented
lib folder֊ը լավը չէ՞ր, որ helpers ես սարքել։ Տարբերությունը չեմ զգա

2023-02-15 11:15 UTC, zidder requested changes

2023-02-15 11:15 UTC, zidder commented on .pylintrc
> +[MASTER]
չէ, էլի, եթե կուզես՝ քու մոտ օգտագործե։ Մենք լինտ էնելու միտք ունեինք, բայց մարդիկ դեմ էին

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
class֊ի անունը շփոթեցնող է, կգրե՞ս ինչի համար է ինքը

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/custom_scene.py
> +        self.wait(0.5)
իմ կարծիքով էս ավելորդ է, բայց եթե կուզես մնա՝ qarakusi_scene֊ում ավելացրու

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/custom_scene.py
> +class CustomScene(Scene):
Ավելի լավ անուն կմտածե՞ս

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/custom_scene.py
> +        Axes().set_opacity(0.3)
էս տարօրինակ է, բան կփոխվի՞ իրանից

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/custom_scene.py
> +        Axes().set_opacity(0.3)
էս շատ բտի օգտագործվի՞ դեռ։ Եթե հա՝ կարող ես lib֊ում որպես ֆունկցիա սարքել (առանց self.add մասի, էդ Scene֊ում կռնաս էնես)

2023-02-15 11:15 UTC, zidder commented on helpers/movement_problems/helper_functions.py
> +    return res
էս տիպի բաներ չկայի՞ն։ @Gor397 @narek-mkrtumyan

2023-02-15 11:15 UTC, zidder commented on scenes/enumerated/problem_12695/problem_12695.py
> +                         color=ORANGE, stroke_width=5))
մեկ էլ էս, @Gor397 @narek-mkrtumyan

2023-02-15 17:22 UTC, AlternativeFuture commented on .pylintrc
> +[MASTER]
Սա սխալմամբա եկել գիտհաբ

2023-02-15 17:31 UTC, AlternativeFuture commented
Իմ լոգիկայով, լիբը հիմնական լրացուցիչ ֆունկցիոնալա ավելացնում, իսկ հելփփեռը շատ սպոցիֆիկ կոնկրետ խնդիրներից կախված օգնող  ֆոլդեռա, որի մեջ կա movment_problems, այսինքն դրա մեջ հավաքելու եմ մենակ movment ի հետ կապված խնդիրների անիմացիաները գրելուն օգնող բաներ

Կարծում եմ արժի մի հատ քոլլ անենք միասին, քննարկենք

2023-02-15 17:31 UTC, AlternativeFuture commented
կամ պարտադիր չի միասին, եթե ուրիշ ցանկացողներ կան բոլորով  անենք

2023-02-15 17:32 UTC, AlternativeFuture commented on helpers/movement_problems/custom_scene.py
> +        Axes().set_opacity(0.3)
Չհասկացա Արսեն ջան

2023-02-15 17:35 UTC, AlternativeFuture commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
ու ինքը movement_problems ֆոլդերի մեջա

2023-02-15 17:37 UTC, AlternativeFuture commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
երկու կետ ես տալիս, ու տոկոս գտնումա այդ կետերի մեջտեղում եղած ուղագծի վրա երրորդ կետը համաձայն տոկոսի չափի

2023-02-15 17:43 UTC, AlternativeFuture commented on helpers/movement_problems/custom_scene.py
> +class CustomScene(Scene):
Սրա անունը սենցա, որտև չգիտեմ ապագայում ինչ մեթոդներ կավելացնեմ մեջը, ինքը movment_problems ի CustomScene, հիմա եթե ավել կոնկրետ անուն դնեմ, հետագայում մեթոդ ավելացնեմ, չի բրնի կլասի անունի հետ, իսկ եթե այդ ժամանակ փոխեմ, ստիպված կլինեմ բոլոր օգտագործված տեղերում փոխել, իմ կարծիքով լավագույնը կարեմ դնեմ MovmentProblemsCustumScene, եթե կուզես

2023-02-15 17:56 UTC, narek-mkrtumyan commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
էդի մանիմն ունի ոնց, կոչվում ա point_from_proportion կամ տենց մի բան

2023-02-15 18:00 UTC, narek-mkrtumyan commented on helpers/movement_problems/helper_functions.py
> +    return res
ի՞նչ իմաստով, չեմ հասկանում հարցը։ ես սենց բաների համար ֆունկցիա չէի սարքի, որտև 2 տող ա էղածը, ու հետո դզմզելը ավելի հեշտ ա ինձ թվում ա, որ հենց մանիմական ա ամեն ինչ, ոչ թե մերոնցական ։դ տենց թիմում նոր մարդ գալու դեպքում, ու նմանատիպ դեպքերում ավելի հեշտ ա։

չնայած սենց 2 տողը պռոբլեմ չի ստեղծի երևի որ դզմզելու խնդիր առաջանա, չգիտեմ

2023-02-15 18:01 UTC, narek-mkrtumyan commented
որ տենց հարց քննարկելու քոլ անեք, ինձ էլ տեղեկացրեք միանամ էլի

2023-02-15 18:03 UTC, narek-mkrtumyan commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
ու պարտադիր չի ուղիղ լինի վայթե, իրան path ես տալիս, էդ path-ի մեջ էդ հարաբերակցությամբ կետ ա գտնում (հստակ չեմ հիշում, բայց ես տենց մի բան օգտագործել եմ շուտ)

2023-02-15 18:09 UTC, narek-mkrtumyan commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
https://docs.manim.community/en/stable/reference/manim.mobject.types.vectorized_mobject.VMobject.html?highlight=proportion#manim.mobject.types.vectorized_mobject.VMobject.point_from_proportion

2023-02-16 07:50 UTC, zidder commented
մի քանի պատճառ կա, որ չեմ ուզե նոր folder ունենանք․
1. անիմաստ սկզբնական base folder֊ը ծանրաբեռնել չարժե
2. լիբի նպատակների մեջ է օգտակար բան սարքելը, կռնաս շատ սպեցիֆիկ էղնելու դեպքում էլի ֆոլդըր սարքես, դեմ չեմ տոր, բայց ամեն ինչ, ինչը գրես մեջը բտի մեկից ավել տեղ օգտագործելի էղնի ու մաքուր (bug չունենաս, պատճառաբանելով, թե էդ ձև չես օգտագործել)
3. PYTHONPATH֊ով որ ռան կէնենք, մեջը լիբը գրած է, helpers֊ը՝ չէ, չէի ուզենա ավելացնել։ Ընդ որում, python֊ում ինչ֊որ helpers֊ը իմպոռտ էնելուց տարօրինակ բաներ կէղնի մեկ֊մեկ, հենց էդ անունը։ Ինչ֊որ պահի builtin է էղել թե ինչ։ Ես երբեմն խուսափեմկը էդ բառից (utilities կդնեմ հիմնականում)

Ամեն դեպքում ամենակարևորը երևի 2֊ն է, այն է՝ նույն իմաստը ունի lib֊ը, նոր բան պետք չէ։


Եթե դեռ կմտածես օգտակար է helpers ունենալը՝ կռնանք խոսանք, իմանամ ինչը հաշվի չեմ առել։

2023-02-16 07:55 UTC, zidder commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
կլասսի անունն ու `__init__`֊ը ցանկալի է իրար հետ համապատասխան էղնին, այսինքն init էնելուց 3 առգումենտով կոորդինատ սարքելն է շփոթեցնող։

2023-02-16 08:03 UTC, narek-mkrtumyan commented on helpers/movement_problems/helper_functions.py
> +    return res
segment-ի վրա էր ոնց որ տեքստ դրել, որ հետը շարժվի, բան, բայց հիմանականում չէինք օգտագործում, ձեռքով էինք անում ։դ որտև պրոբելեմատիկոտ էր, ընդեղ օլվեյս ռիդռո հենց սկսում ես անել, լիքը բան դարդ ա դառնում

2023-02-17 13:57 UTC, AlternativeFuture commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
Yը միշտ նույննա, դրա համար մի հատա փողանցվում, ու երկու կետերի xը

2023-02-17 14:37 UTC, AlternativeFuture commented
Ես ինչ ավելացրել էմ, արդեն վերջի 5 վիդոներում օգտագործել եմ, էտ հիներից եմ դուրս բերել այն ինչ մեկից ավել անգամա օգտագործվում, ու որը բավականին հեշտացնումա իմ գործը, շարժման խնդիրներ էլ դեռ մի քանի ամիս պետքա սարգեմ

2023-02-17 14:44 UTC, AlternativeFuture commented on helpers/movement_problems/helper_functions.py
> +    return res
մի վիդոի մեջ սենց երկու տող ու սնեց չոտկի բրնցրած մինչև 7 հատ լինումա իմ մոտ, ես մենակ նրանք եմ հանել հիմնական վիդեոի ֆայլից որոնք անիմաստ ժամանակ են խլում, ծրագրավորումը դրա մասին չի՞ որ քեզ համար գործիքներ ստեղծես արագացնելու ու հեշտացնելու ռազռաբոտկի պրոցեսը, ես իհարկե Ձեզ հասկանում եմ, ուզում եք մաքուր լինի, բայց սա live գնացող պրոեկտ չի որ աշխատանքի ընթացքում խդիրներ տա։ Կարելաի ասել մեր պրոեկտը մի սպեցիֆիկ գրադարանա, որ մենք ենք գրում

2023-02-17 16:21 UTC, AlternativeFuture commented on helpers/movement_problems/coordinate.py
> +class Coordinate:
point_from_proportion սա նայեցի, բայց եթե դեմ չեք, իմ գրածը թող մնա, ինձ ավելի հարմար դա օգտագործել

2023-02-17 19:09 UTC, zidder commented on helpers/movement_problems/helper_functions.py
> +    return res
Իմ սածը զուտ էն էր, որ եթե արդեն նույնը գրած կա՝ օգտագրոծենք, ոչ թե ամեն մարդ նորը գրե

2023-02-18 15:45 UTC, AlternativeFuture commented
@zidder  ջան, իսկ եթե enumerated ֆոլդեռի մեջ նդեմ helper ը,  ինչ որ բան կփոխվի քո մտահոգություների մասով ՞

2023-02-20 11:01 UTC, closed without merging

2023-02-20 11:42 UTC, zidder commented
PR֊ը փակելու պատճառ կա՞ր, #150֊ը նույնն է՞