Equality of fractions
qarakusi-am/qarakusi.am pull request #165
Opened 2023-03-03 10:35 UTC by Gor397

2023-03-07 08:24 UTC, zidder requested changes

2023-03-07 08:24 UTC, zidder commented on scenes/lessons/equality_of_fractions/equality_of_fractions.py
> +from ..reducing_fractions.reducing_fractions import getFractionsOnCircle
սպես բաներ ցանկալի է չէնես հիմնականում։ Մե ֆայլի տեղը փխենք, կտրաքի։ Օրինակ text֊ը տպես չի էղնի, միշտ կողքը կպահենք։ Կռնա՞ lib տանիս ուղղակի

2023-03-07 08:24 UTC, zidder commented on scenes/lessons/reducing_fractions/reducing_fractions.py
> +    if numbering and numbering_font_size==None:
```suggestion
    if numbering and numbering_font_size is None:
```

2023-03-07 13:23 UTC, Gor397 commented on scenes/lessons/equality_of_fractions/equality_of_fractions.py
> +from ..reducing_fractions.reducing_fractions import getFractionsOnCircle
մենակ էս 2 տասքում եմ օգտագործում, տանե՞մ

2023-03-07 20:18 UTC, zidder commented on scenes/lessons/equality_of_fractions/equality_of_fractions.py
> +from ..reducing_fractions.reducing_fractions import getFractionsOnCircle
ահա, օքեյ է, կռնաս անունը ըմբես դնես, չխառնվի ուրիշ բանի հետ, ու ֆսյո

2023-03-10 17:45 UTC, zidder approved these changes

2023-03-10 17:56 UTC, merged