Problem 12187
qarakusi-am/qarakusi.am pull request #172
Opened 2023-03-08 17:29 UTC by AlternativeFuture

2023-03-08 21:56 UTC, zidder commented
`enumerated/__init__.py`֊ը պետք է՞

2023-03-08 21:59 UTC, zidder requested changes

2023-03-08 21:59 UTC, zidder commented on lib/movement_problems/__init__.py
>  from lib.movement_problems.coordinate import Coordinate
կարող է՞ մյուսը մեռջես, նոր էս վերցնես

2023-03-08 21:59 UTC, zidder commented on scenes/enumerated/problem_12187/english_text.py
> +CONDITION_2 = r"\text{less digit = small number}"
```suggestion
CONDITION_2 = r"\text{less digits = smaller number}"
```

2023-03-08 21:59 UTC, zidder commented on scenes/enumerated/problem_12187/english_text.py
> +CONDITION_8 = r"\text{9+9+9} > {23}"
էս եթե նույնն է, կռնաս text.py֊ում գրես

2023-03-08 21:59 UTC, zidder commented on scenes/enumerated/problem_12187/problem_12187.py
> +        self.wait()
էս մասը դզվա՞վ

2023-03-09 08:40 UTC, AlternativeFuture commented on scenes/enumerated/problem_12187/problem_12187.py
> +        self.wait()
ահա

2023-03-09 09:20 UTC, AlternativeFuture commented on lib/movement_problems/__init__.py
>  from lib.movement_problems.coordinate import Coordinate
ահա

2023-03-09 15:35 UTC, zidder commented
մյուս բռանչը pull չես էրել, է

2023-03-10 17:27 UTC, AlternativeFuture commented
արեցի, եթե ճիշտ եմ հասկացել

2023-03-12 17:16 UTC, zidder approved these changes

2023-03-13 08:42 UTC, merged