combined pulls
qarakusi-am/qarakusi.am pull request #182
Opened 2023-03-15 14:05 UTC by lilithm98

2023-03-19 11:50 UTC, zidder commented
Շատ եմ քոմմենթներ գրել, բայց ահագինը 6-10 տողը մի տողով փոխարինելու կարճ ձևեր են, մի քանիսը ընդհանրացրած գրեմ․

```python
index = start
while index < end:
    # some code
    index += step
```

կարելի է փոխարինել
```python
for index in range(start, end, step):
     # some code
```
եթե step=1, ապա կարելի է `range(start, end)` գրել, ու, եթե միաժամանակ start=0, կարելի ՝range(end)` գրել


եթե կուզեք նույն կերպ վազել list֊ի էլեմենտների վրայով
```python
for index in range(len(data)):
    # some code with data[index]
```
գրելու փոխարեն կարող եք
```python
for item in data:
    # some code with item
```
գրել։

եթե ընթացքում index֊ը պետք է՝ `for index, item in enumerate(data)`֊ն միաժամանակ երկու բանը կէնե՝ item֊ը index֊ը միաժամանակ կուտա

եթե պետք է մի քանի list֊ի վրայով զուգահեռ վազել՝ `for item1, item2, item3 in zip(list1, list2, list3):`֊ը ավելի հարմար է, քան index֊ով վազելը


string֊երը իրար կպցնելու համար join֊ը հետևյալն ՝, օրինակ
`' some text '.join(['first', 'second', 'third'])`֊ի արդյունքը `'first some text second some text third'` է


pack unpack֊ը հետևյալ տեսքն ունի․
`data = first_variable, second_variable, third_variable`֊ը tuple կսարքե, որի մեջ էդ երեք էլեմենտներն են, հետո հետ քանդելու համար կարող եք ուղղակի նման ձև հակառակ հերթականությամբ = էնել՝ `a, b, c = data`


Եթե հարցեր կան՝ կարող եմ օգնել

նման բաները ահագին կային, ամեն ինչի վրա չեմ գրել, եթե փորձեք փոփոխել՝ կոդը շատ կկարճանա ու ավելի հեշտ կկարդամ, ամեն ինչը չեմ կարդացել դեռ

2023-03-20 09:33 UTC, zidder requested changes

2023-03-21 20:25 UTC, zidder commented on scenes/lessons/7th_class/10_5_2_divisibility_rules/english_text.py
> +is_a_divisor=" is a divider of these numbers"
ավելի կարևոր մասը՝ տեքստը չի ուղղվել

2023-03-21 20:38 UTC, zidder commented on scenes/enumerated/problem_12714/problem_12714.py
> +
remove, please

2023-03-21 20:38 UTC, zidder commented on scenes/lessons/7th_class/numeric_expression_value/english_text.py
in case you don't have any texts, don't create text files at all and don't import from them

2023-03-21 20:38 UTC, zidder commented on scenes/lessons/7th_class/statistics/statistics/statistics.py
> +from . import text
հիշեցում

2023-03-27 11:12 UTC, zidder approved these changes

2023-03-27 11:12 UTC, zidder commented on scenes/lessons/7th_class/numeric_expression_value/text.py
> +]
կարիքը չկա, ուղղակի իրանից import մի էրեք

2023-03-27 13:29 UTC, lilithm98 commented on scenes/lessons/7th_class/numeric_expression_value/text.py
> +]
hetagayum task number a avelanalu, der uxaki hstak vorna

2023-04-10 14:40 UTC, merged