problem_12706
qarakusi-am/qarakusi.am pull request #183
Opened 2023-03-16 10:04 UTC by AlternativeFuture

2023-03-19 11:07 UTC, zidder requested changes

2023-03-19 11:07 UTC, zidder commented on scenes/enumerated/problem_12706/english_text.py
> +CONDITION_1_0 = r"\text{Delete one digit to get}"
maybe `remove` instead of `delete?

2023-03-19 11:07 UTC, zidder commented on scenes/enumerated/problem_12706/armenian_text.py
> +CONDITION_1_1 = r"\text{որ ստացվի հնարավորին մեծ թիվ}"
```suggestion
CONDITION_1_1 = r"\text{որ ստացվի հնարավորինս մեծ թիվ}"
```

2023-03-19 11:07 UTC, zidder commented on scenes/enumerated/problem_12706/english_text.py
> +CONDITION_5 = r"\text{the number will be 11 digits long}"
`the result will be 11 digit number`
Զուտ հայերենի նույն ձևով էղնի

2023-03-19 11:07 UTC, zidder commented on scenes/enumerated/problem_12706/text.py
> +NUMS = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
էս երկուսից մենակ ներքևինը կմնա վերջում, վերևինը կռնաս ջնջես

2023-03-20 12:33 UTC, AlternativeFuture commented on scenes/enumerated/problem_12706/armenian_text.py
> +CONDITION_1_1 = r"\text{որ ստացվի հնարավորին մեծ թիվ}"
Սմբատը ասեց պետք չի վերջի ս―ն

2023-03-20 12:34 UTC, AlternativeFuture commented on scenes/enumerated/problem_12706/english_text.py
> +CONDITION_1_0 = r"\text{Delete one digit to get}"
Good idea

2023-03-20 13:45 UTC, zidder commented on scenes/enumerated/problem_12706/armenian_text.py
> +CONDITION_1_1 = r"\text{որ ստացվի հնարավորին մեծ թիվ}"
բայց "հնարավորին"֊ը իմ իմանալով հայերեն չէ

2023-03-20 13:46 UTC, zidder approved these changes

2023-03-20 13:55 UTC, AlternativeFuture commented on scenes/enumerated/problem_12706/armenian_text.py
> +CONDITION_1_1 = r"\text{որ ստացվի հնարավորին մեծ թիվ}"
ես գրել էի հնարավորինս, Սմբատը ասեց ս֊ն հանի

2023-03-20 17:09 UTC, merged