Problem12753
qarakusi-am/qarakusi.am pull request #220
Opened 2023-04-07 13:17 UTC by AlternativeFuture

2023-04-20 10:26 UTC, zidder commented
@Gor397 , կամաց֊կամաց քեզ փոխանցեմ approve սխմելու պատասխանատվությունը,
կնայե՞ս

2023-04-21 05:09 UTC, Gor397 commented
> @Gor397 , կամաց֊կամաց քեզ փոխանցեմ approve սխմելու պատասխանատվությունը,
> կնայե՞ս

կնայեմ 😃

2023-04-21 14:42 UTC, Gor397 requested changes

2023-04-21 14:42 UTC, Gor397 commented on scenes/enumerated/problem_12753/problem_12753.py
> +        positions_gago = ([1.8, 0.4, 0], [2.7, 0.4, 0], [3.6, 0.4, 0], [4.5, 0.4, 0])
սենց հատիկ հատիկ կոորդինատները գրելը դժվար չի՞, կարաս arrange անես հետո մնացած բաները ըստ `gago`-ի էլեմենտների կոորդինատների տաս (օրինակ `set_x()`-ով ընենց անես, որ իրար համապատասխան տառերը/թվերը, նույն x-ը ունենան), սենց որ font_size-ը փոխես, գրածդ կոորդինատներն էլ կարողա կարիք լինի փոխելու

2023-04-21 14:42 UTC, Gor397 commented on scenes/enumerated/problem_12753/problem_12753.py
> +        positions_19 = ([3.6, -0.6, 0], [4.5, -0.6, 0])
սրա փոխարեն էլ կարաս `next_to()`-ով անես

2023-04-21 14:42 UTC, Gor397 commented on scenes/enumerated/problem_12753/text.py
> +CONDITION_6 = [r"\text{ 1 }", r"\text{ 9 }"]
ստեղ որ `\text` չգրես ավելի ճիշտ չի լինի՞, font-ը չի համընկնում իրա վերևի թվերի հետ (էս համ էլ վիդեոյի ռիվյու էր)

2023-04-21 14:42 UTC, Gor397 commented on scenes/enumerated/problem_12753/text.py
> +FOUR = r"4"
ստեղի r-երը օգուտ տալի՞ս են
@zidder կարողա՞ շատ եմ խորանում, ու սենց բաներին ուշադրություն դարձնել պետք չի

2023-04-21 14:56 UTC, AlternativeFuture commented on scenes/enumerated/problem_12753/problem_12753.py
> +        positions_19 = ([3.6, -0.6, 0], [4.5, -0.6, 0])
սկզբից տենց եմ արել, էլեմենտները շարժվում էին տրանֆորմի արդյունքում

2023-04-21 16:42 UTC, zidder commented on scenes/enumerated/problem_12753/text.py
> +CONDITION_6 = [r"\text{ 1 }", r"\text{ 9 }"]
սփեյսերը չի էղնի եթե տեքստ չգրե, չէ՞

2023-04-21 17:00 UTC, Gor397 commented on scenes/enumerated/problem_12753/text.py
> +CONDITION_6 = [r"\text{ 1 }", r"\text{ 9 }"]
problem_12753.py ֆայլի 130-132 տողերը նայի ըտեղա օգտագործում, ու իրանց առանձին առանձին move_to-ա անում, ըտեղ սփեյսը օգուտ չի տալիս կարծում եմ

2023-04-22 07:05 UTC, AlternativeFuture commented on scenes/enumerated/problem_12753/problem_12753.py
> +        girl = SimpleSVGMobject("people/children/girl_4").scale(1.5)
մենակ girl ով աղջկան սպիտակա ցույց տալիս, բացի դա, երբ ֆոլդերի անուն ենք փոխում  pycharm֊ը օգտագործված տեղերումելա փոխում

2023-04-22 07:30 UTC, AlternativeFuture commented on scenes/enumerated/problem_12753/problem_12753.py
> +        positions_gago = ([1.8, 0.4, 0], [2.7, 0.4, 0], [3.6, 0.4, 0], [4.5, 0.4, 0])
Դժվարա, բայց էնքան բան եմ փորձեցի, որ այս արդյունքը ստանամ, որ սենց էլ ստացվեց լավա
մյուս անգամ հաշվի կառնեմ

2023-04-23 08:02 UTC, Gor397 commented on scenes/enumerated/problem_12753/problem_12753.py
> +        girl = SimpleSVGMobject("people/children/girl_4").scale(1.5)
էտ սպիտակ svg-ի ու էլի մի քանիսի հետ խնդիր կա, չպետքա սպիտակ լինի, լավա, որ նկատեցիր, որովհետև արդեն հրապարակած վիդեոներ կային, որտեղ էս svg-ին գունավորա, բայց github-ի կոդերով ռենդռ անելուց՝ սպիտակ, էտ ես կփորձեմ դզել, նոր aprove կանեմ

2023-04-23 08:51 UTC, Gor397 commented
woman_1.svg-ի ու girl_4.svg-ի անունները փոխել եմ colored_girl_1.svg colored_woman_1.svg, քանի որ problem_10107-ում էլ են օգտագործվում ու հրապարակած տարբերակում գունավոր էին, հետո կոդերում բաներ էին փոխվել և գունավոր ու սպիտակ svg-ները խառնվել էին իրար, բոլորը դարձել էին սպիտակ և անհամապտասխանություն էր առաջացել հրապարակած վիդեոյի ու github-ի կոդերի միջև

2023-04-23 08:52 UTC, Gor397 approved these changes

2023-04-23 09:15 UTC, merged