Numberline
qarakusi-am/qarakusi.am pull request #59
Opened 2022-09-23 08:25 UTC by a-arakelian

newly made animation, ready to merge

2022-09-23 12:40 UTC, zidder requested changes

2022-09-23 12:40 UTC, zidder commented on scenes/enumerated/problem_00000/problem_00000.py
> +            return animation
Can you keep the tab size consistent?

2022-09-23 21:20 UTC, narek-mkrtumyan commented on scenes/enumerated/problem_00000/problem_00000.py
> +from this import s
վաօ դզեց, չգիտեի որ տենց կարելի ա ։դ

2022-09-23 21:22 UTC, narek-mkrtumyan reviewed
մեկ էլ եթե դժվար չի, էս սաղ տար scenes/lessons/numberline/-ի մեջ, ու numberline/-ում կլինի նաև թվային առանցքի վրա բաժանման մասին վիդյոն

2022-09-26 15:03 UTC, narek-mkrtumyan approved these changes

2022-09-26 20:05 UTC, zidder approved these changes

2022-09-27 03:49 UTC, merged