Problem 11334
qarakusi-am/qarakusi.am pull request #61
Opened 2022-09-24 12:26 UTC by Vachagan11

մի հատ կփորձե՞ք ձեր մոտ հայերեն ու անգլերեն ռան անել, իմ մոտ երկու դեպքում էլ հայերեն ա ստացվում

2022-09-28 08:07 UTC, narek-mkrtumyan requested changes

2022-09-28 08:07 UTC, narek-mkrtumyan commented on lib/constants.py
> +DEFAULT_STROKE_WIDTH = 6
manim-ը սենց փոփոխական ունի իրա կոնստանտներում, անունը փոխի, համընկնումներ չլինեն

2022-09-28 08:07 UTC, narek-mkrtumyan commented on lib/constants.py
> +DEFAULT_STROKE_WIDTH = 6
ու մի քիչ ավելի լավ նկարագրող անուն թող լինի, DEFAUKT_SEGMENT_STROLE_WIDTH խոսքի, որտև մանիմական stroke width-ը բոլորի վրա ա աշխատում, իսկ քոնը մենակ սեգմենտի համար ա

2022-09-28 12:54 UTC, Vachagan11 commented on lib/constants.py
> +DEFAULT_STROKE_WIDTH = 6
էդ արեցի, բայց մի հատ մոտդ անգլերեն ռենդրի

2022-10-02 10:17 UTC, narek-mkrtumyan commented
@zidder ստեղ անգլերեն որ փորձում ենք ռենդենք, հայերենն ա ռենդում մեկ ա, ինչի՞ց կլինի

2022-10-02 10:17 UTC, narek-mkrtumyan approved these changes

2022-10-02 10:19 UTC, narek-mkrtumyan commented
approve պիտի չանեի, մենակ փոփոխությունն էի ուզում ըփրուվ անեի, սենց էղավ ։դ

2022-10-02 11:36 UTC, Vachagan11 commented
@zidder
իմ ու Նարեկի մոտ անգլերեն ռան էնելու տեղը, հայերեն կենե
ու չգիտենք խի

2022-10-02 21:47 UTC, zidder requested changes
Ֆոնտը փոքրացրու, շատ մեծ է

2022-10-02 21:47 UTC, zidder commented on scenes/enumerated/problem_11334/text.py
> +from lib.constants import LanguageConfig
```suggestion
from constants import LanguageConfig
```

2022-10-02 21:47 UTC, zidder commented on scenes/enumerated/problem_11334/problem_11334.py
> +            Segment(seg_5_part_3.get_right(), seg_5_part_3.get_right() + np.array([part_length.get_value(), 0, 0]))
you can create functions for those kind of repetitive code blocks.

2022-10-02 21:47 UTC, zidder commented on scenes/enumerated/problem_11334/text.py
> +from lib.constants import LanguageConfig
ծծծ

2022-10-04 13:59 UTC, zidder commented on lib/constants.py
> +ARMTEX = TexTemplate()
Էս մեռջած չէ՞ր, pull կէնե՞ս

2022-10-04 14:03 UTC, Vachagan11 commented on lib/constants.py
> +ARMTEX = TexTemplate()
ինձ թվում ա, մինչև վախտին մերջելը իմ մոտ էս բրանչում լոկալ փոխել էի ու մինչև մերջելը էս pr-ը սարքել

2022-10-09 07:38 UTC, narek-mkrtumyan commented on lib/constants.py
> +ARMTEX = TexTemplate()
բա հմի ինչ ենք անում էս մոմենդը

2022-10-09 07:38 UTC, narek-mkrtumyan commented
թե դզմզելու բան կա, անենք, մերջենք գնա

2022-10-09 13:23 UTC, Vachagan11 commented
> թե դզմզելու բան կա, անենք, մերջենք գնա

վաբշետը խնդրի համարը մոռացել եմ գրեմ

2022-11-19 16:16 UTC, Vachagan11 commented
@zidder

2022-11-19 18:14 UTC, zidder approved these changes

2022-11-19 18:28 UTC, merged